//Generated by Gemini on 2024-06-17
float hash12(vec2 p) {
    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    // 归一化坐标，中心为(0,0)
    vec2 uv = (fragCoord - 0.5 * iResolution.xy) / iResolution.y;
    vec3 finalCol = vec3(0.0);

    // 绘制 64 个粒子
    for(float i=0.0; i<64.0; i++) {
        // 1. 为每个粒子生成唯一的随机 ID (Hash)
        // 我们利用循环索引 i 来生成不同的随机数
        float id = hash12(vec2(i, 123.456));
        float id2 = hash12(vec2(i, 456.789));

        // 2. 赋予每个粒子不同的 $P_0$ 移动路径
        // 初始位置随机化 (-1 到 1)
        vec2 origin = vec2(id, id2) * 2.0 - 1.0;
        
        // 移动速度和方向随机化
        vec2 dir = vec2(cos(id * 6.28), sin(id * 6.28));
        float speed = 0.1 + id2 * 0.2;
        
        // 核心：随时间变化的 P0
        // 使用 fract(iTime) 让粒子在 0-5 秒内循环运动
        float t = fract(iTime * 0.2 + id); 
        vec2 p0 = origin + dir * t * speed;

        // 3. 计算当前像素到这个移动点 p0 的距离场
        float d = length(uv - p0);

        // 4. 计算粒子亮度 (利用你之前掌握的衰减公式)
        // 添加呼吸闪烁效果：smoothstep 让粒子在出生和消失时淡入淡出
        float fadeInOut = smoothstep(0.0, 0.2, t) * smoothstep(1.0, 0.8, t);
        float spark = (0.002 / d) * fadeInOut;

        // 5. 颜色分配：每个粒子颜色微调
        vec3 col = vec3(0.5 + 0.5 * sin(id * 6.28), 0.4, 1.0);
        
        // 6. 累加到最终画布 (叠加发光)
        finalCol += col * spark;
    }

    fragColor = vec4(finalCol, 1.0);
}